"""
VELYNX Node Review CLI
======================

Interactive terminal tool to review, approve, reject, or skip autonomous
graph proposals generated by ``auto_learner.py``.

Run with::

    python -m backend.cognition.review_nodes

Approved nodes are written into ``data/concepts.json`` and
``data/knowledge_graph.db``.  Rejected nodes are discarded.  Skipped nodes
remain in ``data/proposed_nodes.json`` for later review.
"""

from __future__ import annotations

import json
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any

from backend.memory._sqlite import connect as open_connection
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt
from rich.table import Table
from rich.text import Text

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "data"
PROPOSED_PATH = DATA_DIR / "proposed_nodes.json"
CONCEPTS_PATH = DATA_DIR / "concepts.json"
KNOWLEDGE_DB_PATH = DATA_DIR / "knowledge_graph.db"

console = Console()


def _db_conn():
    KNOWLEDGE_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = open_connection(str(KNOWLEDGE_DB_PATH))
    c = conn.cursor()
    c.execute("""CREATE TABLE IF NOT EXISTS concepts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT UNIQUE NOT NULL,
        domain TEXT DEFAULT 'general',
        description TEXT
    )""")
    c.execute("""CREATE TABLE IF NOT EXISTS relationships (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        source TEXT NOT NULL,
        relation TEXT NOT NULL,
        target TEXT NOT NULL
    )""")
    conn.commit()
    return conn


def _concept_exists_in_db(conn: sqlite3.Connection, concept: str) -> bool:
    c = conn.cursor()
    c.execute("SELECT 1 FROM concepts WHERE name = ?", (concept,))
    return c.fetchone() is not None


def _insert_concept_db(conn: sqlite3.Connection, concept: str, definition: str) -> None:
    if not _concept_exists_in_db(conn, concept):
        conn.execute(
            "INSERT INTO concepts (name, domain, description) VALUES (?, ?, ?)",
            (concept, "auto_learned", definition),
        )


def _insert_relationship_db(
    conn: sqlite3.Connection, source: str, relation: str, target: str
) -> None:
    c = conn.cursor()
    c.execute(
        "SELECT 1 FROM relationships WHERE source = ? AND relation = ? AND target = ?",
        (source, relation, target),
    )
    if not c.fetchone():
        conn.execute(
            "INSERT INTO relationships (source, relation, target) VALUES (?, ?, ?)",
            (source, relation, target),
        )


def _load_concepts_json() -> dict:
    if CONCEPTS_PATH.exists():
        try:
            return json.loads(CONCEPTS_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {"nodes": {}}


def _save_concepts_json(data: dict) -> None:
    CONCEPTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONCEPTS_PATH.write_text(
        json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def _concept_in_concepts_json(concepts_data: dict, concept: str) -> bool:
    return concept in (concepts_data.get("nodes") or {})


def _add_to_concepts_json(
    concepts_data: dict, concept: str, definition: str, origin: str = "auto_learned"
) -> None:
    concepts_data.setdefault("nodes", {})
    concepts_data["nodes"][concept] = {
        "definition": definition,
        "origin": origin,
        "confidence": 0.5,
    }


def load_proposals() -> dict | None:
    if not PROPOSED_PATH.exists():
        return None
    try:
        raw = PROPOSED_PATH.read_text(encoding="utf-8").strip()
        if not raw:
            return None
        return json.loads(raw)
    except (json.JSONDecodeError, OSError):
        return None


def save_proposals(payload: dict) -> None:
    PROPOSED_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROPOSED_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def build_display_panel(proposal: dict, idx: int, total: int) -> Panel:
    concept = proposal.get("concept", "unknown")
    definition = proposal.get("definition", "") or "(no WordNet definition)"
    synonyms = proposal.get("synonyms", [])
    matched = proposal.get("matched_existing_concepts", [])
    proposed_edges = proposal.get("proposed_edges", [])
    origin = proposal.get("origin", "unknown")

    body = Text()
    body.append(f"Concept: ", style="bold bright_cyan")
    body.append(f"{concept}\n\n", style="bold white")

    body.append(f"Origin: ", style="dim")
    body.append(f"{origin}\n", style="italic")

    body.append(f"Definition: ", style="bold yellow")
    body.append(f"{definition}\n")

    if synonyms:
        body.append(f"Synonyms: ", style="bold green")
        body.append(", ".join(synonyms))
        body.append("\n")

    if matched:
        body.append(f"Already in graph: ", style="bold magenta")
        body.append(", ".join(matched))
        body.append("\n")

    if proposed_edges:
        body.append(f"\nProposed Edges:\n", style="bold underline")
        for edge in proposed_edges:
            s = edge.get("source", "?")
            r = edge.get("relationship", "relates_to")
            t = edge.get("target", "?")
            body.append(f"  [{s}] ", style="cyan")
            body.append(f"--{r}--> ", style="bright_green")
            body.append(f"[{t}]\n", style="cyan")
    else:
        body.append(f"\n(no existing-concept links — ", style="dim")
        body.append("standalone node", style="italic dim")
        body.append(")\n", style="dim")

    title = f"Proposal {idx + 1}/{total}"
    return Panel(body, title=title, border_style="bright_blue", padding=(1, 2))


def _approve(proposal: dict, conn: sqlite3.Connection, concepts_data: dict) -> None:
    concept = proposal["concept"]
    definition = proposal.get("definition", "")
    proposed_edges = proposal.get("proposed_edges", [])

    if not _concept_in_concepts_json(concepts_data, concept):
        _add_to_concepts_json(concepts_data, concept, definition)

    _insert_concept_db(conn, concept, definition)

    for edge in proposed_edges:
        source = edge.get("source", concept)
        relationship = edge.get("relationship", "relates_to")
        target = edge.get("target", "")
        if target:
            _insert_relationship_db(conn, source, relationship, target)

    console.print(f"  [green]Approved:[/] {concept} → added to graph.")


def _reject(proposal: dict) -> None:
    console.print(f"  [red]Rejected:[/] {proposal['concept']} → discarded.")


def _skip(proposal: dict) -> None:
    console.print(f"  [yellow]Skipped:[/] {proposal['concept']} → stays in quarantine.")


def review(proposals: list[dict]) -> tuple[list[dict], list[dict], list[dict]]:
    approved: list[dict] = []
    rejected: list[dict] = []
    skipped: list[dict] = []

    conn = _db_conn()
    concepts_data = _load_concepts_json()

    total = len(proposals)
    for idx, proposal in enumerate(proposals):
        console.clear()
        console.print(build_display_panel(proposal, idx, total))
        console.print()

        choice = Prompt.ask(
            "[A]pprove, [R]eject, or [S]kip?",
            choices=["a", "r", "s", "A", "R", "S"],
            default="s",
            show_choices=False,
            show_default=False,
        ).lower()

        if choice == "a":
            _approve(proposal, conn, concepts_data)
            approved.append(proposal)
        elif choice == "r":
            _reject(proposal)
            rejected.append(proposal)
        else:
            _skip(proposal)
            skipped.append(proposal)

        if idx < total - 1:
            Prompt.ask("\nPress Enter to continue...", default="")

    conn.commit()
    conn.close()
    _save_concepts_json(concepts_data)

    return approved, rejected, skipped


def print_summary(approved: list, rejected: list, skipped: list) -> None:
    table = Table(title="Review Summary", border_style="bright_blue")
    table.add_column("Verdict", style="bold")
    table.add_column("Count", justify="right")
    table.add_column("Concepts")

    table.add_row(
        "[green]Approved[/]",
        str(len(approved)),
        ", ".join(p["concept"] for p in approved) or "—",
    )
    table.add_row(
        "[red]Rejected[/]",
        str(len(rejected)),
        ", ".join(p["concept"] for p in rejected) or "—",
    )
    table.add_row(
        "[yellow]Skipped[/]",
        str(len(skipped)),
        ", ".join(p["concept"] for p in skipped) or "—",
    )

    console.print()
    console.print(table)


def main() -> int:
    payload = load_proposals()

    if payload is None:
        console.print(
            Panel(
                "No pending nodes in quarantine.",
                border_style="yellow",
                padding=(1, 2),
            )
        )
        return 0

    proposals: list[dict] = payload.get("proposals", [])
    if not proposals:
        console.print(
            Panel(
                "No pending nodes in quarantine.",
                border_style="yellow",
                padding=(1, 2),
            )
        )
        return 0

    approved, rejected, skipped = review(proposals)

    payload["proposals"] = skipped
    payload["last_reviewed"] = datetime.now().isoformat()
    save_proposals(payload)

    print_summary(approved, rejected, skipped)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
