"""P1 Research Operating System — projections and drift detection (invariant K1).

*One record, many projections.* The store is the only writable scientific state;
every registry, dashboard and report is generated from it and is never
hand-edited. A projection that disagrees with the store is a build failure, not a
document.

Two functions matter here and they are deliberately different in kind:

``render_laboratory_state``
    Generates a document that has no hand-written source. Safe to overwrite on
    every build because nobody authors it.

``drift``
    Does *not* overwrite the twelve hand-maintained registries under
    ``science/skb/``. Those contain human prose — interpretation, caveats,
    reasoning — that a generator cannot reproduce and must not destroy. Instead
    it verifies that they do not *contradict* the store on the facts a machine
    can check: which records exist, and what status each carries.

That split is the whole design. Regenerating human interpretation would be
vandalism; leaving it unchecked is how three representations drift apart. The
answer is to generate what is derived and verify what is authored.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .model import COLLECTION_BY_KEY, ID_PATTERN
from .store import Finding, Store

#: Hand-maintained registries, mapped to the collection each projects.
REGISTRY_FILES: dict[str, str] = {
    "science/skb/01_HYPOTHESIS_REGISTRY.md": "hypotheses",
    "science/skb/02_EXPERIMENT_REGISTRY.md": "experiments",
    "science/skb/03_MECHANISM_REGISTRY.md": "mechanisms",
    "science/skb/04_ASSUMPTION_REGISTRY.md": "assumptions",
    "science/skb/05_UNKNOWN_REGISTRY.md": "unknowns",
    "science/skb/06_SCIENTIFIC_DEBT_REGISTRY.md": "scientific_debt",
    "science/skb/07_NEGATIVE_RESULTS_REGISTRY.md": "negative_results",
    "science/skb/08_OBSERVATION_REGISTRY.md": "observations",
    "science/skb/10_SCIENTIFIC_DECISION_HISTORY.md": "decisions",
}

GENERATED_DIR = Path("docs/ros/generated")

_GENERATED_BANNER = (
    "<!-- GENERATED BY `python -m ros render`. Do not edit. "
    "Edit science/SKB_RECORDS_v1.0.yaml and re-render. -->"
)


@dataclass(frozen=True)
class DriftReport:
    findings: tuple[Finding, ...]

    @property
    def clean(self) -> bool:
        return not any(f.severity == "error" for f in self.findings)

    def render(self) -> str:
        if not self.findings:
            return "no drift: every registry agrees with the store"
        return "\n".join(str(f) for f in self.findings)


def _ids_in(text: str, prefix: str) -> set[str]:
    return {m.group(0) for m in ID_PATTERN.finditer(text) if m.group(1) == prefix}


def drift(store: Store, root: Path | str = ".") -> DriftReport:
    """Verify hand-maintained registries against the store.

    Checks two things per registry, both mechanical:

    * every store record of that collection is mentioned in its registry;
    * every identifier of that collection mentioned in the registry exists in
      the store.

    A record present in one and absent from the other is an error, because the
    two representations then disagree about what the laboratory knows.
    """
    root = Path(root)
    findings: list[Finding] = []

    for relative, collection_key in REGISTRY_FILES.items():
        path = root / relative
        collection = COLLECTION_BY_KEY.get(collection_key)
        if collection is None:
            continue
        prefix = collection.prefix

        if not path.exists():
            findings.append(
                Finding(
                    "PROJ-301",
                    "warning",
                    relative,
                    f"registry projecting {collection_key!r} does not exist",
                )
            )
            continue

        text = path.read_text(encoding="utf-8", errors="replace")
        documented = _ids_in(text, prefix)
        stored = {r.identifier for r in store.by_collection(collection_key)}

        for missing in sorted(stored - documented):
            findings.append(
                Finding(
                    "PROJ-310",
                    "error",
                    relative,
                    f"{missing} is in the store but absent from this registry",
                )
            )
        for extra in sorted(documented - stored):
            findings.append(
                Finding(
                    "PROJ-311",
                    "error",
                    relative,
                    f"{extra} appears in this registry but resolves to no store record",
                )
            )

    return DriftReport(tuple(findings))


def _status_table(store: Store, key: str, limit: int | None = None) -> list[str]:
    rows = ["| ID | Status | Title |", "|---|---|---|"]
    records = sorted(store.by_collection(key), key=lambda r: r.identifier)
    if limit is not None:
        records = records[:limit]
    for record in records:
        title = re.sub(r"\s+", " ", record.title)[:88]
        rows.append(f"| `{record.identifier}` | {record.status or '—'} | {title} |")
    return rows


def render_laboratory_state(store: Store, root: Path | str = ".") -> Path:
    """Generate the laboratory state projection. Returns the written path."""
    from .governance import load_registration
    from .kpi import compute
    from .propagation import audit_all

    root = Path(root)
    registration = load_registration(root)
    metrics = compute(store, registration)
    reports = audit_all(store)

    lines: list[str] = [
        _GENERATED_BANNER,
        "",
        "# P1 Laboratory State",
        "",
        f"- **Store:** `{store.path.as_posix()}`",
        f"- **Store digest:** `{store.content_hash()[:32]}`",
        f"- **SKB version:** {store.header.get('version', 'unknown')}",
        f"- **Phase:** {store.header.get('phase', 'unknown')}",
        "",
        "## Admissibility",
        "",
    ]

    if registration.active:
        lines.append(
            "Registration is **active**. Runs may bear evidence subject to their manifest."
        )
    else:
        lines += [
            "**Registration is not active.** Under Article L-11 every run in this",
            "repository is engineering-only and produces no admissible evidence.",
            "",
            "Outstanding:",
            "",
        ]
        lines += [f"- {gap}" for gap in registration.missing()]
    lines.append("")

    lines += ["## Key indicators", "", "| Metric | Value |", "|---|---|"]
    for metric in metrics:
        lines.append(f"| {metric.name} | {metric.rendered} |")
    lines.append("")

    lines += ["## Record counts", "", "| Collection | Count |", "|---|---:|"]
    for key, count in store.counts().items():
        lines.append(f"| {key} | {count} |")
    lines.append("")

    incomplete = [r for r in reports if not r.complete]
    lines += ["## Propagation", ""]
    lines.append(
        f"{len(reports)} experiment(s) with propagation due; "
        f"{len(reports) - len(incomplete)} complete."
    )
    lines.append("")
    if incomplete:
        lines += ["| Experiment | Outstanding obligations |", "|---|---|"]
        for report in incomplete:
            names = ", ".join(o.obligation.value for o in report.outstanding)
            lines.append(f"| `{report.experiment_id}` | {names} |")
        lines.append("")

    lines += ["## Hypotheses", ""] + _status_table(store, "hypotheses") + [""]
    lines += ["## Scientific debt", ""] + _status_table(store, "scientific_debt") + [""]
    lines += ["## Unknowns", ""] + _status_table(store, "unknowns") + [""]

    target = root / GENERATED_DIR / "LABORATORY_STATE.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


__all__ = ["DriftReport", "GENERATED_DIR", "REGISTRY_FILES", "drift", "render_laboratory_state"]
